language: python
python:
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
env:
  global:
    - CC_TEST_REPORTER_ID=a0a14b1d60e6b757fe5001b53530fde4ce942b99e0841d9b6ffafbda640af15c
    - CT_REGISTER_MODE=False
    - PORT=5037
    - API_VERSION=v1
    - LOCAL_URL=http://127.0.0.1:5037
    - CT_URL=http://127.0.0.1:9000
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ

before_script:
  - echo -e "$GS_PRO_SERVICE_ACCOUNT" | base64 -d > spreadsheet.json
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest --cov=proconfig --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
