prod:
  image: vizzuality/gs-pro-config:1.0.0${STAGING}
  ports:
    - "6700"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: gs-pro-config${STAGING}
