version: "3"
services:
  test:
    build: .
    ports:
      - "6700:6700"
    container_name: gs-pro-config
    environment:
      PORT: 6700
      GS_PRO_SERVICE_ACCOUNT: $GS_PRO_SERVICE_ACCOUNT
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "True"
    command: test
