version: "3"
services:
  test:
    build: .
    ports:
      - "6700:6700"
    container_name: gs-pro-config
    environment:
      PORT: 6700
      GS_PRO_SERVICE_ACCOUNT: $GS_PRO_SERVICE_ACCOUNT
      CT_URL: http://mymachine:9000
      CT_REGISTER_MODE: 'false'
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
    command: test
