version: "3"
services:
  develop:
    build: .
    ports:
      - "6700:6700"
    container_name: gs-pro-config-develop
    environment:
      PORT: 6700
      GS_PRO_SERVICE_ACCOUNT: $GS_PRO_SERVICE_ACCOUNT
      ENVIRONMENT: dev
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    command: develop
    volumes:
      - ./proconfig:/opt/proconfig/proconfig
    restart: always
