apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: gs-pro-config
  name: gs-pro-config
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: gs-pro-config
    spec:
      containers:
      - name: gs-pro-config
        image: vizzuality/gs-pro-config
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "6700"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://gs-pro-config.gfw.svc.cluster.local:6700
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: GS_PRO_SERVICE_ACCOUNT
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: GS_PRO_SERVICE_ACCOUNT

        ports:
          - containerPort: 6700

      restartPolicy: Always
