apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gs-pro-config
  namespace: gfw
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gs-pro-config
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
